# pre-commit <https://pre-commit.com>

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-toml
      - id: check-yaml

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: '22.8.0'
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: '6.1.0'
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-pyproject

default_language_version:
  python: python3
