version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - graphviz
    - libsndfile1
  tools:
    python: '3.10'
  commands:
    - pip install hatch
    - hatch run docs:build $READTHEDOCS_OUTPUT/html
