[tool.poetry]
name = "medkit-lib"
version = "0.12.0"
description = "A Python library for a learning health system"
readme = "README.md"
repository = "https://gitlab.inria.fr/heka/medkit/"
documentation = "https://heka.gitlabpages.inria.fr/medkit/"
authors = ["HeKA Research Team"]
maintainers = [
    "medkit-maintainers <medkit-maintainers@inria.fr>"
]

license = "MIT"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Medical Science Apps."
]
packages = [
  { include = "medkit" }
]

[tool.poetry.dependencies]
python = ">=3.8, <4.0"
duptextfinder = "*"
flashtext = "^2.7"
numpy = "*"
pyaml = "*"
requests = "*"
smart-open = "*"
soundfile = "*"
tqdm = "*"
typing-extensions = "*"
anyascii = "^0.3"
intervaltree = "*"
wheel = "*"
iamsystem = ">=0.3"

# optional
edsnlp = {version = "^0.9", optional = true}
feather-format = {version = "^0.4", optional = true}
packaging = {version = "*", optional = true}
pandas = {version = "^1.4", optional = true}
PyRuSH = {version = "^1.0", optional = true}
pyannote-core = {version = "^5.0.0", optional = true}
pyannote-metrics = {version = "^3.2.0", optional = true}
pyannote-audio = {version = "^3.1", optional = true}
quickumls = {version = "^1.4", optional = true}
resampy = {version = "^0.4", optional = true}
sacremoses = {version = "*", optional = true}
sentencepiece = {version = "*", optional = true}
seqeval = {version = "^1.2.2", optional = true}
spacy = {version = "^3.4", optional = true}
speechbrain = {version = "^0.5", optional = true}
torch = {version = "^2.1.1", optional = true}
torchaudio = {version = "^2.1.1", optional = true}
transformers = {version = "^4.21", optional = true}
unqlite =  {version = "^0.9.6", optional = true}
webrtcvad = {version = "^2.0", optional = true}
pysrt = {version = "^1.1.2", optional = true}
scikit-learn = {version = "^1.3.2", optional = true}

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
pytest-mock = "*"
pre-commit = "*"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
jupyter-book = "^0.13"
matplotlib = "*"
pandas = {version = "^1.4", python = ">=3.8, <4.0"}
spacy = "^3.4"
sphinx = ">=4.3.3"
sphinxcontrib-mermaid = ">=0.8"
sphinx-toolbox = "*"

[tool.poetry.extras]
edsnlp = ["edsnlp"]
hf-entity-matcher = ["torch", "transformers"]
hf-transcriber = ["torchaudio", "transformers"]
hf-translator = ["sacremoses", "sentencepiece", "torch", "transformers"]
hf-utils = ["transformers"]
metrics-diarization = ["pyannote-core", "pyannote-metrics"]
metrics-text-classification = ["scikit-learn"]
metrics-ner = ["seqeval","transformers","torch"]
metrics-transcription = ["speechbrain"]
pa-speaker-detector = ["pyannote-audio", "torch"]
quick-umls = ["packaging", "quickumls", "unqlite"]
resampler = ["resampy"]
rush-sentence-tokenizer = ["PyRush"]
sb-transcriber = ["speechbrain", "torch", "transformers"]
spacy = ["spacy"]
srt-io-converter = ["pysrt"]
syntactic-relation-extractor = ["spacy"]
training = ["torch"]
umls-coder-normalizer = ["feather-format", "pandas", "torch", "transformers"]
webrtc-voice-detector = ["webrtcvad"]
all = [
    "edsnlp",
    "feather-format",
    "packaging",
    "pandas",
    "PyRuSH",
    "pyannote-core",
    "pyannote-metrics",
    "pyannote-audio",
    "quickumls",
    "resampy",
    "sacremoses",
    "sentencepiece",
    "seqeval",
    "spacy",
    "speechbrain",
    "torch",
    "torchaudio",
    "transformers",
    "unqlite",
    "webrtcvad",
    "pysrt",
    "scikit-learn",
]

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"

[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py38"
src = ["medkit", "tests"]

[tool.ruff.lint]
select = ["B", "C", "E", "F", "I001", "W"]
ignore = ["E203", "C408", "C901", "E402", "E501"]

[tool.ruff.lint.isort]
known-first-party = ["medkit"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
dirty = true
pattern = "(?P<base>\\d+(\\.\\d+)*)"
latest-tag = true
style = "semver"
